---
driver:
  name: dokken
  use_sudo: false
  #run_command: /usr/sbin/init
  network:
   - ["private_network", {ip: "192.168.34.34"}]



transport:
  name: dokken

provisioner:
  name: dokken


verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
#  - name: centos-7

suites:
  - name: default
    data_bags_path: test/fixtures/default/data_bags
    run_list:
      - recipe[git::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
